### ISSUE TITLE
Feature request/bug report

### ISSUE THREAD

**Issue by JessieLjubovic** [drmproductions/ActiveCollabInlineTimers#1]
Hi,

This is Jessie from Active Collab support team.

Our clients reported that all their time entries are having 15-minute minimum entry. 

I did some tests and this is not happening in my account (I can add only a minute by using your awesome extension :). 

Is this a bug? 

Looking forward to hearing from you!

**Comment by crewnecktech** [comment]
I'm guessing this is from the extension preferences we setup to be similar to the AC Desktop timer.  Most likely the extension preference for "Minimum Entry" needs set to 0, and "Rounding Interval" needs set to 0 minutes.

![image](https://cloud.githubusercontent.com/assets/685328/24179106/776eec80-0e83-11e7-9313-01cc96e3bc11.png)

I just set these both as mentioned and don't see a 15-minute minimum, so I think we're good, but let me know if you can make it mess up!

**Comment by crewnecktech** [comment]
> using your awesome extension :)

Thanks for the compliment by the way!  Thanks for the awesome project management system.. :)

**Comment by JessieLjubovic** [comment]
Oooooh, I missed these settings, sorry :) You've been really helpful, thanks a lot for the help and the fast reply! :)

And thanks for the great feedback, I'm glad that you're loving our tool :) 

Cheers!

**Comment by crewnecktech** [comment]
Happy to help! 👍
