### ISSUE TITLE
Don't immediately destroy popup

### ISSUE THREAD

**Issue by TitanNano** [drmproductions/ActiveCollabInlineTimers#4]
Certain actions in the popup window send off a command to the server script and then immediately destroy the window with `window.close()`. Because Firefox sends messages between windows asynchronously, an exception is raised when the window has been destroyed before the message has been sent. The easiest way to fix this, is to wait for the response before closing the window.

**Comment by luveti** [comment]
Hey TitanNano! Thank you for the pull requests! I'll look into these as soon as I get a chance :)
