### ISSUE TITLE
Timer context options menu no longer accessible/clickable with latest ActiveCollab update.

### ISSUE THREAD

**Issue by BigAndy29** [drmproductions/ActiveCollabInlineTimers#6]
Since the latest update of ActiveCollab (10th Jan 2019), the three dot menu can no longer be selected on the **My Work** page (to the left of the timer). The timer can be started (red timer) and paused (yellow timer) but it is currently impossible to select the individual timer menu button, moving the mouse cursor towards the menu results in its disappearance/ hiding it behind the menu on the left hand side.

![image](https://user-images.githubusercontent.com/46570026/50980200-0a5bb680-14f0-11e9-9533-10fc917aa2d8.png)

It is accessible if I run Inspector in Chrome and hide the main side bar component <aside id="main_sidebar" ...>

UPDATE:
I've since been told that it works if it's used via the **Projects** page, it just appears to be an issue on **My Works**.

**Comment by BigAndy29** [comment]
Additional:
It is accessible if I run Inspector in Chrome and hide the main side bar component <aside id="main_sidebar" ...>

**Comment by crewnecktech** [comment]
@BigAndy29 I'm not sure as we don't have the latest version of AC.  I'll see if we can get the latest version or if they can create a pull request to fix it!

**Comment by BigAndy29** [comment]
@crewnecktech , thanks for the response.

The overlapping main menu with the timer menu issue also occurs if you try to access it via People > [Staff member name] > the tasks list on their page as well.

**Comment by crewnecktech** [comment]
@BigAndy29 It would appear Active Collab is looking to add their own so they're not interested in getting this fixed at the moment.  I'm sure we could work up a temp fix, but I don't have any access to the current version to test and see what needs changed.   I'm open to anyone submitting a pull request, but for the time being it looks like I don't have a good way to fix this.

**Comment by BigAndy29** [comment]
@crewnecktech , no worries I've got a few ways to get around it locally for now

**Comment by crewnecktech** [comment]
Yesterday we received the new version of ActiveCollab and have now updated the extension to support version 6!  Please update to the latest version and you should be set!
