### ISSUE TITLE
active collab timers not appearing in project view

### ISSUE THREAD

**Issue by SolveSD** [drmproductions/ActiveCollabInlineTimers#7]
Since the recent update, the inline timers do not appear next to the tasks in project view
![Capture](https://user-images.githubusercontent.com/49191416/55394386-1d9e8100-5537-11e9-86f2-4c6b008d5312.JPG)

**Comment by crewnecktech** [comment]
Unfortunately, we don't have access to the new version.  ActiveCollab has told us they have a new timing solution coming, and are not interested in helping us get on the new version at this time.

If you have an idea and can submit a pull request we'd be happy to review and get this updated!  We just have no way to work with it at the moment.

**Comment by crewnecktech** [comment]
Yesterday we received the new version of ActiveCollab and have now updated the extension to support version 6!  Please update to the latest version and you should be set!
